// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQfigViCcVTkhQljCRotJJMDf02aCTkY',
    appId: '1:1067082398499:android:0aca815fbeba19709c6a96',
    messagingSenderId: '1067082398499',
    projectId: 'notera-flutter-project',
    storageBucket: 'notera-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITSZIGJEm987FLb8o7NgVtYj_fNeyiRo',
    appId: '1:1067082398499:ios:76e3e4b0725e1ed99c6a96',
    messagingSenderId: '1067082398499',
    projectId: 'notera-flutter-project',
    storageBucket: 'notera-flutter-project.appspot.com',
    iosClientId: '1067082398499-ufrhpks4g1sg14tg57h7pmg12i6pqbla.apps.googleusercontent.com',
    iosBundleId: '42web.jcaproject2-techshop.notera',
  );
}
